/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    categories: Category;
    services: Service;
    jobs: Job;
    media: Media;
    'applicant-files': ApplicantFile;
    'job-applications': JobApplication;
    'contact-submissions': ContactSubmission;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    jobs: JobsSelect<false> | JobsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'applicant-files': ApplicantFilesSelect<false> | ApplicantFilesSelect<true>;
    'job-applications': JobApplicationsSelect<false> | JobApplicationsSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale:
    | ('false' | 'none' | 'null')
    | false
    | null
    | ('en' | 'ar' | 'de' | 'fr' | 'es')
    | ('en' | 'ar' | 'de' | 'fr' | 'es')[];
  globals: {
    header: Header;
    footer: Footer;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'en' | 'ar' | 'de' | 'fr' | 'es';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL path segment. Changing this on a live page needs a redirect entry.
   */
  slug: string;
  layout?:
    | (
        | HeroBlock
        | ServiceHeroBlock
        | HiringModelsBlock
        | LogoCloudBlock
        | IndustriesBlock
        | TalentShowcaseBlock
        | CardGridBlock
        | StatsBlock
        | ProcessBlock
        | TestimonialsBlock
        | FaqBlock
        | PostsTeaserBlock
        | TechStackBlock
        | CtaBlock
        | RichTextBlock
        | MediaBlock
        | ContactBlock
        | BookingBlock
        | SharedSectionBlock
      )[]
    | null;
  /**
   * Excludes this page from sitemap.xml (18.5).
   */
  hideFromSitemap?: boolean | null;
  /**
   * Locales with approved translations. Drives hreflang and the language switcher (14.8/14.9).
   */
  availableLocales?: ('en' | 'ar' | 'de' | 'fr' | 'es')[] | null;
  publishedAt?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    /**
     * Only set this when the page must point at a different canonical (18.3).
     */
    canonicalOverride?: string | null;
    /**
     * Excludes the page from search results and the sitemap (18.13).
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  eyebrow?: string | null;
  heading: string;
  /**
   * Optional second line rendered in the brand colour.
   */
  headingAccent?: string | null;
  body?: string | null;
  trustLine?: string | null;
  /**
   * Optional illustration — renders the split hero (copy at the start, art at the end).
   */
  media?: (number | null) | Media;
  /**
   * Cycled in the headline. Leave empty to use the accent line instead.
   */
  rotatingWords?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  bullets?:
    | {
        text: string;
        icon?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  ctas?:
    | {
        variant?: ('primary' | 'secondary' | 'ghost') | null;
        link?: {
          type?: ('internal' | 'route' | 'external') | null;
          /**
           * Visible link text. A link with no label is not rendered.
           */
          label?: string | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null)
            | ({
                relationTo: 'services';
                value: number | Service;
              } | null)
            | ({
                relationTo: 'jobs';
                value: number | Job;
              } | null);
          route?:
            ('/' | '/blog' | '/services' | '/careers' | '/contact' | '/meeting' | '/about' | '/meet-fika-ai') | null;
          url?: string | null;
          newTab?: boolean | null;
          /**
           * Optional. Sent as the GA4 event name when clicked (22.5).
           */
          analyticsId?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Simple stat row. Use the mosaic below for the bento layout instead.
   */
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  mosaic?:
    | {
        kind?: ('image' | 'stat') | null;
        span?: ('normal' | 'tall' | 'wide') | null;
        tone?: ('green' | 'emerald' | 'indigo' | 'teal') | null;
        corner?: ('tl' | 'tr' | 'bl' | 'br') | null;
        image?: (number | null) | Media;
        value?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional #id for in-page links. Lowercase, no spaces.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen readers and search (18.11). Leave empty ONLY for purely decorative images.
   */
  alt?: string | null;
  /**
   * Decorative image — renders with an empty alt attribute.
   */
  decorative?: boolean | null;
  caption?: string | null;
  credit?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    content?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * URL path segment. Changing this on a live page needs a redirect entry.
   */
  slug: string;
  excerpt?: string | null;
  heroImage?: (number | null) | Media;
  contentFormat?: ('richText' | 'html') | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  htmlContent?: string | null;
  /**
   * CTA, FAQ or related blocks under the article body.
   */
  layout?:
    | (
        | HeroBlock
        | ServiceHeroBlock
        | HiringModelsBlock
        | LogoCloudBlock
        | IndustriesBlock
        | TalentShowcaseBlock
        | CardGridBlock
        | StatsBlock
        | ProcessBlock
        | TestimonialsBlock
        | FaqBlock
        | PostsTeaserBlock
        | TechStackBlock
        | CtaBlock
        | RichTextBlock
        | MediaBlock
        | ContactBlock
        | BookingBlock
        | SharedSectionBlock
      )[]
    | null;
  category?: (number | null) | Category;
  /**
   * Shown as the byline and used in Article schema (19.4).
   */
  author?: (number | null) | User;
  tags?: string[] | null;
  relatedPosts?: (number | Post)[] | null;
  availableLocales?: ('en' | 'ar' | 'de' | 'fr' | 'es')[] | null;
  featured?: boolean | null;
  publishedAt?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    /**
     * Only set this when the page must point at a different canonical (18.3).
     */
    canonicalOverride?: string | null;
    /**
     * Excludes the page from search results and the sitemap (18.13).
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServiceHeroBlock".
 */
export interface ServiceHeroBlock {
  heading: string;
  /**
   * Colour of the band behind the hero — the comps alternate per service.
   */
  heroTone?: ('mint' | 'blue' | 'blush' | 'amber' | 'sky' | 'coral' | 'teal' | 'gold' | 'lilac') | null;
  /**
   * Each line renders as its own paragraph.
   */
  body?: string | null;
  /**
   * Bold closing line under the paragraphs.
   */
  closer?: string | null;
  highlights?:
    | {
        icon?: (number | null) | Media;
        text: string;
        id?: string | null;
      }[]
    | null;
  formTitle?: string | null;
  /**
   * Optional #id for in-page links. Lowercase, no spaces.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'serviceHero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HiringModelsBlock".
 */
export interface HiringModelsBlock {
  eyebrow?: string | null;
  heading: string;
  models?:
    | {
        title: string;
        tone?: ('amber' | 'lavender' | 'blue') | null;
        stats?:
          | {
              value: string;
              label: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  benefitsTitle?: string | null;
  benefits?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  ctas?:
    | {
        variant?: ('primary' | 'secondary' | 'ghost') | null;
        link?: {
          type?: ('internal' | 'route' | 'external') | null;
          /**
           * Visible link text. A link with no label is not rendered.
           */
          label?: string | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null)
            | ({
                relationTo: 'services';
                value: number | Service;
              } | null)
            | ({
                relationTo: 'jobs';
                value: number | Job;
              } | null);
          route?:
            ('/' | '/blog' | '/services' | '/careers' | '/contact' | '/meeting' | '/about' | '/meet-fika-ai') | null;
          url?: string | null;
          newTab?: boolean | null;
          /**
           * Optional. Sent as the GA4 event name when clicked (22.5).
           */
          analyticsId?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Optional #id for in-page links. Lowercase, no spaces.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hiringModels';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  /**
   * URL path segment. Changing this on a live page needs a redirect entry.
   */
  slug: string;
  summary: string;
  icon?: (number | null) | Media;
  layout?:
    | (
        | HeroBlock
        | ServiceHeroBlock
        | HiringModelsBlock
        | LogoCloudBlock
        | IndustriesBlock
        | TalentShowcaseBlock
        | CardGridBlock
        | StatsBlock
        | ProcessBlock
        | TestimonialsBlock
        | FaqBlock
        | PostsTeaserBlock
        | TechStackBlock
        | CtaBlock
        | RichTextBlock
        | MediaBlock
        | ContactBlock
        | BookingBlock
        | SharedSectionBlock
      )[]
    | null;
  /**
   * Set for SEO landing pages under a parent service. Drives breadcrumbs (18.9) and internal linking (18.10).
   */
  parent?: (number | null) | Service;
  relatedServices?: (number | Service)[] | null;
  /**
   * Lower numbers appear first in the Services overview.
   */
  order?: number | null;
  /**
   * Roles listed under this service in the header Services mega-menu. Leave empty to keep the service out of the menu columns.
   */
  menuRoles?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  availableLocales?: ('en' | 'ar' | 'de' | 'fr' | 'es')[] | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    /**
     * Only set this when the page must point at a different canonical (18.3).
     */
    canonicalOverride?: string | null;
    /**
     * Excludes the page from search results and the sitemap (18.13).
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogoCloudBlock".
 */
export interface LogoCloudBlock {
  variant?: ('statement' | 'badges') | null;
  eyebrow?: string | null;
  heading?: string | null;
  statement?: {
    before?: string | null;
    /**
     * Rendered in the brand colour.
     */
    highlight?: string | null;
    after?: string | null;
  };
  logos?:
    | {
        image: number | Media;
        name: string;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  marquee?: boolean | null;
  /**
   * Optional #id for in-page links. Lowercase, no spaces.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'logoCloud';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IndustriesBlock".
 */
export interface IndustriesBlock {
  eyebrow?: string | null;
  heading: string;
  /**
   * Optional second line rendered in the brand colour.
   */
  headingAccent?: string | null;
  body?: string | null;
  industries?:
    | {
        label: string;
        tone?: ('pink' | 'mint' | 'lilac' | 'teal' | 'blue') | null;
        icon?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional #id for in-page links. Lowercase, no spaces.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'industries';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TalentShowcaseBlock".
 */
export interface TalentShowcaseBlock {
  eyebrow?: string | null;
  heading: string;
  /**
   * Optional second line rendered in the brand colour.
   */
  headingAccent?: string | null;
  body?: string | null;
  bullets?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  roles?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  panelTitle?: string | null;
  /**
   * Background of the engineer panel.
   */
  panelTone?: ('grey' | 'mint') | null;
  /**
   * Alternate this between stacked showcases.
   */
  side?: ('copyLeft' | 'copyRight') | null;
  people?:
    | {
        name: string;
        role: string;
        /**
         * e.g. 5+ Years
         */
        experience?: string | null;
        /**
         * Match %
         */
        match?: number | null;
        evaluated?: boolean | null;
        avatar?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  ctas?:
    | {
        variant?: ('primary' | 'secondary' | 'ghost') | null;
        link?: {
          type?: ('internal' | 'route' | 'external') | null;
          /**
           * Visible link text. A link with no label is not rendered.
           */
          label?: string | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null)
            | ({
                relationTo: 'services';
                value: number | Service;
              } | null)
            | ({
                relationTo: 'jobs';
                value: number | Job;
              } | null);
          route?:
            ('/' | '/blog' | '/services' | '/careers' | '/contact' | '/meeting' | '/about' | '/meet-fika-ai') | null;
          url?: string | null;
          newTab?: boolean | null;
          /**
           * Optional. Sent as the GA4 event name when clicked (22.5).
           */
          analyticsId?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Optional #id for in-page links. Lowercase, no spaces.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'talentShowcase';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs".
 */
export interface Job {
  id: number;
  title: string;
  /**
   * URL path segment. Changing this on a live page needs a redirect entry.
   */
  slug: string;
  summary: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  requirements?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  benefits?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  department?: string | null;
  location: string;
  workModel: 'onsite' | 'hybrid' | 'remote';
  employmentType: 'FULL_TIME' | 'PART_TIME' | 'CONTRACTOR' | 'TEMPORARY' | 'INTERN';
  countryCode?: string | null;
  city?: string | null;
  /**
   * Schema expiry. Blank = 90 days after publish.
   */
  validThrough?: string | null;
  availableLocales?: ('en' | 'ar' | 'de' | 'fr' | 'es')[] | null;
  /**
   * Closing a role removes its JobPosting schema and disables the form (10.9).
   */
  roleStatus: 'open' | 'closed';
  publishedAt?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    /**
     * Only set this when the page must point at a different canonical (18.3).
     */
    canonicalOverride?: string | null;
    /**
     * Excludes the page from search results and the sitemap (18.13).
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardGridBlock".
 */
export interface CardGridBlock {
  /**
   * Business styles the cards like the "All Businesses Types" section; compliance renders full-width certification rows (About page).
   */
  variant?: ('plain' | 'business' | 'compliance' | 'numbered') | null;
  eyebrow?: string | null;
  heading: string;
  /**
   * Optional second line rendered in the brand colour.
   */
  headingAccent?: string | null;
  body?: string | null;
  columns?: ('2' | '3' | '4') | null;
  cards?:
    | {
        icon?: (number | null) | Media;
        title: string;
        /**
         * Compliance rows only — the bold one-liner under the title.
         */
        subtitle?: string | null;
        body?: string | null;
        /**
         * Compliance rows only — the tinted "What It Means for You" strip.
         */
        note?: string | null;
        link?: {
          type?: ('internal' | 'route' | 'external') | null;
          /**
           * Visible link text. A link with no label is not rendered.
           */
          label?: string | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null)
            | ({
                relationTo: 'services';
                value: number | Service;
              } | null)
            | ({
                relationTo: 'jobs';
                value: number | Job;
              } | null);
          route?:
            ('/' | '/blog' | '/services' | '/careers' | '/contact' | '/meeting' | '/about' | '/meet-fika-ai') | null;
          url?: string | null;
          newTab?: boolean | null;
          /**
           * Optional. Sent as the GA4 event name when clicked (22.5).
           */
          analyticsId?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  ctas?:
    | {
        variant?: ('primary' | 'secondary' | 'ghost') | null;
        link?: {
          type?: ('internal' | 'route' | 'external') | null;
          /**
           * Visible link text. A link with no label is not rendered.
           */
          label?: string | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null)
            | ({
                relationTo: 'services';
                value: number | Service;
              } | null)
            | ({
                relationTo: 'jobs';
                value: number | Job;
              } | null);
          route?:
            ('/' | '/blog' | '/services' | '/careers' | '/contact' | '/meeting' | '/about' | '/meet-fika-ai') | null;
          url?: string | null;
          newTab?: boolean | null;
          /**
           * Optional. Sent as the GA4 event name when clicked (22.5).
           */
          analyticsId?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Optional #id for in-page links. Lowercase, no spaces.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cardGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock".
 */
export interface StatsBlock {
  heading?: string | null;
  items?:
    | {
        value: string;
        label: string;
        /**
         * Corner-chip glyph (About comp).
         */
        icon?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional #id for in-page links. Lowercase, no spaces.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'stats';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProcessBlock".
 */
export interface ProcessBlock {
  eyebrow?: string | null;
  heading: string;
  /**
   * Optional second line rendered in the brand colour.
   */
  headingAccent?: string | null;
  body?: string | null;
  /**
   * Rendered as an ordered list — step numbers come from the order.
   */
  steps?:
    | {
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional #id for in-page links. Lowercase, no spaces.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'process';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock".
 */
export interface TestimonialsBlock {
  eyebrow?: string | null;
  heading: string;
  /**
   * Optional second line rendered in the brand colour.
   */
  headingAccent?: string | null;
  body?: string | null;
  items?:
    | {
        quote: string;
        authorName: string;
        authorRole: string;
        avatar?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  stats?:
    | {
        value: string;
        label: string;
        /**
         * Star icon
         */
        star?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional #id for in-page links. Lowercase, no spaces.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonials';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock".
 */
export interface FaqBlock {
  eyebrow?: string | null;
  heading: string;
  /**
   * Optional second line rendered in the brand colour.
   */
  headingAccent?: string | null;
  body?: string | null;
  items?:
    | {
        question: string;
        answer: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Only enable on pages where the FAQ is the primary content (18.8/19.3).
   */
  emitSchema?: boolean | null;
  /**
   * Small line above the closing button.
   */
  footnote?: string | null;
  ctas?:
    | {
        variant?: ('primary' | 'secondary' | 'ghost') | null;
        link?: {
          type?: ('internal' | 'route' | 'external') | null;
          /**
           * Visible link text. A link with no label is not rendered.
           */
          label?: string | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null)
            | ({
                relationTo: 'services';
                value: number | Service;
              } | null)
            | ({
                relationTo: 'jobs';
                value: number | Job;
              } | null);
          route?:
            ('/' | '/blog' | '/services' | '/careers' | '/contact' | '/meeting' | '/about' | '/meet-fika-ai') | null;
          url?: string | null;
          newTab?: boolean | null;
          /**
           * Optional. Sent as the GA4 event name when clicked (22.5).
           */
          analyticsId?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Optional #id for in-page links. Lowercase, no spaces.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PostsTeaserBlock".
 */
export interface PostsTeaserBlock {
  eyebrow?: string | null;
  heading: string;
  /**
   * Optional second line rendered in the brand colour.
   */
  headingAccent?: string | null;
  body?: string | null;
  limit?: number | null;
  category?: (number | null) | Category;
  ctas?:
    | {
        variant?: ('primary' | 'secondary' | 'ghost') | null;
        link?: {
          type?: ('internal' | 'route' | 'external') | null;
          /**
           * Visible link text. A link with no label is not rendered.
           */
          label?: string | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null)
            | ({
                relationTo: 'services';
                value: number | Service;
              } | null)
            | ({
                relationTo: 'jobs';
                value: number | Job;
              } | null);
          route?:
            ('/' | '/blog' | '/services' | '/careers' | '/contact' | '/meeting' | '/about' | '/meet-fika-ai') | null;
          url?: string | null;
          newTab?: boolean | null;
          /**
           * Optional. Sent as the GA4 event name when clicked (22.5).
           */
          analyticsId?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Optional #id for in-page links. Lowercase, no spaces.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'postsTeaser';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * URL path segment. Changing this on a live page needs a redirect entry.
   */
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TechStackBlock".
 */
export interface TechStackBlock {
  eyebrow?: string | null;
  heading: string;
  /**
   * Optional second line rendered in the brand colour.
   */
  headingAccent?: string | null;
  body?: string | null;
  groups?:
    | {
        name: string;
        items?:
          | {
              name: string;
              logo?: (number | null) | Media;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional #id for in-page links. Lowercase, no spaces.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'techStack';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBlock".
 */
export interface CtaBlock {
  eyebrow?: string | null;
  heading: string;
  body?: string | null;
  /**
   * Optional illustration above the button.
   */
  media?: (number | null) | Media;
  ctas?:
    | {
        variant?: ('primary' | 'secondary' | 'ghost') | null;
        link?: {
          type?: ('internal' | 'route' | 'external') | null;
          /**
           * Visible link text. A link with no label is not rendered.
           */
          label?: string | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null)
            | ({
                relationTo: 'services';
                value: number | Service;
              } | null)
            | ({
                relationTo: 'jobs';
                value: number | Job;
              } | null);
          route?:
            ('/' | '/blog' | '/services' | '/careers' | '/contact' | '/meeting' | '/about' | '/meet-fika-ai') | null;
          url?: string | null;
          newTab?: boolean | null;
          /**
           * Optional. Sent as the GA4 event name when clicked (22.5).
           */
          analyticsId?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  tone?: ('brand' | 'ink' | 'subtle' | 'feature' | 'band' | 'panel') | null;
  /**
   * Optional #id for in-page links. Lowercase, no spaces.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock".
 */
export interface RichTextBlock {
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  width?: ('prose' | 'full' | 'panel') | null;
  /**
   * Optional #id for in-page links. Lowercase, no spaces.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  caption?: string | null;
  width?: ('container' | 'full') | null;
  /**
   * Optional #id for in-page links. Lowercase, no spaces.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactBlock".
 */
export interface ContactBlock {
  eyebrow?: string | null;
  heading: string;
  /**
   * Optional second line rendered in the brand colour.
   */
  headingAccent?: string | null;
  body?: string | null;
  showOffices?: boolean | null;
  showForm?: boolean | null;
  /**
   * Optional #id for in-page links. Lowercase, no spaces.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contact';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BookingBlock".
 */
export interface BookingBlock {
  eyebrow?: string | null;
  heading: string;
  /**
   * Optional second line rendered in the brand colour.
   */
  headingAccent?: string | null;
  body?: string | null;
  /**
   * Overrides the default booking URL from Site Settings.
   */
  calendlyUrl?: string | null;
  /**
   * Optional #id for in-page links. Lowercase, no spaces.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'booking';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SharedSectionBlock".
 */
export interface SharedSectionBlock {
  /**
   * Pulls the section from the home page in the current locale. Edit it on home and every page using it updates — there is nothing to keep in sync here.
   */
  section:
    | 'techStack'
    | 'process'
    | 'industries'
    | 'testimonials'
    | 'fika'
    | 'certifications'
    | 'faq'
    | 'posts'
    | 'contact'
    | 'ctaBand';
  id?: string | null;
  blockName?: string | null;
  blockType: 'sharedSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Editors manage content. Admins also manage users and settings.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applicant-files".
 */
export interface ApplicantFile {
  id: number;
  originalName?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-applications".
 */
export interface JobApplication {
  id: number;
  fullName: string;
  email: string;
  phone?: string | null;
  linkedin?: string | null;
  job: number | Job;
  cv: number | ApplicantFile;
  coverNote?: string | null;
  status?: ('new' | 'reviewing' | 'interviewing' | 'rejected' | 'hired') | null;
  dedupeKey?: string | null;
  locale?: string | null;
  sourcePath?: string | null;
  utmSource?: string | null;
  utmMedium?: string | null;
  utmCampaign?: string | null;
  referrer?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  fullName: string;
  email: string;
  phone?: string | null;
  company?: string | null;
  subject: string;
  message: string;
  status?: ('new' | 'replied' | 'closed' | 'spam') | null;
  locale?: string | null;
  sourcePath?: string | null;
  utmSource?: string | null;
  utmMedium?: string | null;
  utmCampaign?: string | null;
  referrer?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'jobs';
        value: number | Job;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'applicant-files';
        value: number | ApplicantFile;
      } | null)
    | ({
        relationTo: 'job-applications';
        value: number | JobApplication;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        serviceHero?: T | ServiceHeroBlockSelect<T>;
        hiringModels?: T | HiringModelsBlockSelect<T>;
        logoCloud?: T | LogoCloudBlockSelect<T>;
        industries?: T | IndustriesBlockSelect<T>;
        talentShowcase?: T | TalentShowcaseBlockSelect<T>;
        cardGrid?: T | CardGridBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        process?: T | ProcessBlockSelect<T>;
        testimonials?: T | TestimonialsBlockSelect<T>;
        faq?: T | FaqBlockSelect<T>;
        postsTeaser?: T | PostsTeaserBlockSelect<T>;
        techStack?: T | TechStackBlockSelect<T>;
        cta?: T | CtaBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        contact?: T | ContactBlockSelect<T>;
        booking?: T | BookingBlockSelect<T>;
        sharedSection?: T | SharedSectionBlockSelect<T>;
      };
  hideFromSitemap?: T;
  availableLocales?: T;
  publishedAt?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonicalOverride?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  headingAccent?: T;
  body?: T;
  trustLine?: T;
  media?: T;
  rotatingWords?:
    | T
    | {
        text?: T;
        id?: T;
      };
  bullets?:
    | T
    | {
        text?: T;
        icon?: T;
        id?: T;
      };
  ctas?:
    | T
    | {
        variant?: T;
        link?:
          | T
          | {
              type?: T;
              label?: T;
              reference?: T;
              route?: T;
              url?: T;
              newTab?: T;
              analyticsId?: T;
            };
        id?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  mosaic?:
    | T
    | {
        kind?: T;
        span?: T;
        tone?: T;
        corner?: T;
        image?: T;
        value?: T;
        label?: T;
        id?: T;
      };
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServiceHeroBlock_select".
 */
export interface ServiceHeroBlockSelect<T extends boolean = true> {
  heading?: T;
  heroTone?: T;
  body?: T;
  closer?: T;
  highlights?:
    | T
    | {
        icon?: T;
        text?: T;
        id?: T;
      };
  formTitle?: T;
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HiringModelsBlock_select".
 */
export interface HiringModelsBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  models?:
    | T
    | {
        title?: T;
        tone?: T;
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
        id?: T;
      };
  benefitsTitle?: T;
  benefits?:
    | T
    | {
        text?: T;
        id?: T;
      };
  ctas?:
    | T
    | {
        variant?: T;
        link?:
          | T
          | {
              type?: T;
              label?: T;
              reference?: T;
              route?: T;
              url?: T;
              newTab?: T;
              analyticsId?: T;
            };
        id?: T;
      };
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogoCloudBlock_select".
 */
export interface LogoCloudBlockSelect<T extends boolean = true> {
  variant?: T;
  eyebrow?: T;
  heading?: T;
  statement?:
    | T
    | {
        before?: T;
        highlight?: T;
        after?: T;
      };
  logos?:
    | T
    | {
        image?: T;
        name?: T;
        url?: T;
        id?: T;
      };
  marquee?: T;
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IndustriesBlock_select".
 */
export interface IndustriesBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  headingAccent?: T;
  body?: T;
  industries?:
    | T
    | {
        label?: T;
        tone?: T;
        icon?: T;
        id?: T;
      };
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TalentShowcaseBlock_select".
 */
export interface TalentShowcaseBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  headingAccent?: T;
  body?: T;
  bullets?:
    | T
    | {
        text?: T;
        id?: T;
      };
  roles?:
    | T
    | {
        label?: T;
        id?: T;
      };
  panelTitle?: T;
  panelTone?: T;
  side?: T;
  people?:
    | T
    | {
        name?: T;
        role?: T;
        experience?: T;
        match?: T;
        evaluated?: T;
        avatar?: T;
        id?: T;
      };
  ctas?:
    | T
    | {
        variant?: T;
        link?:
          | T
          | {
              type?: T;
              label?: T;
              reference?: T;
              route?: T;
              url?: T;
              newTab?: T;
              analyticsId?: T;
            };
        id?: T;
      };
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardGridBlock_select".
 */
export interface CardGridBlockSelect<T extends boolean = true> {
  variant?: T;
  eyebrow?: T;
  heading?: T;
  headingAccent?: T;
  body?: T;
  columns?: T;
  cards?:
    | T
    | {
        icon?: T;
        title?: T;
        subtitle?: T;
        body?: T;
        note?: T;
        link?:
          | T
          | {
              type?: T;
              label?: T;
              reference?: T;
              route?: T;
              url?: T;
              newTab?: T;
              analyticsId?: T;
            };
        id?: T;
      };
  ctas?:
    | T
    | {
        variant?: T;
        link?:
          | T
          | {
              type?: T;
              label?: T;
              reference?: T;
              route?: T;
              url?: T;
              newTab?: T;
              analyticsId?: T;
            };
        id?: T;
      };
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock_select".
 */
export interface StatsBlockSelect<T extends boolean = true> {
  heading?: T;
  items?:
    | T
    | {
        value?: T;
        label?: T;
        icon?: T;
        id?: T;
      };
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProcessBlock_select".
 */
export interface ProcessBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  headingAccent?: T;
  body?: T;
  steps?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock_select".
 */
export interface TestimonialsBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  headingAccent?: T;
  body?: T;
  items?:
    | T
    | {
        quote?: T;
        authorName?: T;
        authorRole?: T;
        avatar?: T;
        id?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        star?: T;
        id?: T;
      };
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock_select".
 */
export interface FaqBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  headingAccent?: T;
  body?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  emitSchema?: T;
  footnote?: T;
  ctas?:
    | T
    | {
        variant?: T;
        link?:
          | T
          | {
              type?: T;
              label?: T;
              reference?: T;
              route?: T;
              url?: T;
              newTab?: T;
              analyticsId?: T;
            };
        id?: T;
      };
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PostsTeaserBlock_select".
 */
export interface PostsTeaserBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  headingAccent?: T;
  body?: T;
  limit?: T;
  category?: T;
  ctas?:
    | T
    | {
        variant?: T;
        link?:
          | T
          | {
              type?: T;
              label?: T;
              reference?: T;
              route?: T;
              url?: T;
              newTab?: T;
              analyticsId?: T;
            };
        id?: T;
      };
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TechStackBlock_select".
 */
export interface TechStackBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  headingAccent?: T;
  body?: T;
  groups?:
    | T
    | {
        name?: T;
        items?:
          | T
          | {
              name?: T;
              logo?: T;
              id?: T;
            };
        id?: T;
      };
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBlock_select".
 */
export interface CtaBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  body?: T;
  media?: T;
  ctas?:
    | T
    | {
        variant?: T;
        link?:
          | T
          | {
              type?: T;
              label?: T;
              reference?: T;
              route?: T;
              url?: T;
              newTab?: T;
              analyticsId?: T;
            };
        id?: T;
      };
  tone?: T;
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock_select".
 */
export interface RichTextBlockSelect<T extends boolean = true> {
  content?: T;
  width?: T;
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  caption?: T;
  width?: T;
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactBlock_select".
 */
export interface ContactBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  headingAccent?: T;
  body?: T;
  showOffices?: T;
  showForm?: T;
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BookingBlock_select".
 */
export interface BookingBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  headingAccent?: T;
  body?: T;
  calendlyUrl?: T;
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SharedSectionBlock_select".
 */
export interface SharedSectionBlockSelect<T extends boolean = true> {
  section?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  heroImage?: T;
  contentFormat?: T;
  content?: T;
  htmlContent?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        serviceHero?: T | ServiceHeroBlockSelect<T>;
        hiringModels?: T | HiringModelsBlockSelect<T>;
        logoCloud?: T | LogoCloudBlockSelect<T>;
        industries?: T | IndustriesBlockSelect<T>;
        talentShowcase?: T | TalentShowcaseBlockSelect<T>;
        cardGrid?: T | CardGridBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        process?: T | ProcessBlockSelect<T>;
        testimonials?: T | TestimonialsBlockSelect<T>;
        faq?: T | FaqBlockSelect<T>;
        postsTeaser?: T | PostsTeaserBlockSelect<T>;
        techStack?: T | TechStackBlockSelect<T>;
        cta?: T | CtaBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        contact?: T | ContactBlockSelect<T>;
        booking?: T | BookingBlockSelect<T>;
        sharedSection?: T | SharedSectionBlockSelect<T>;
      };
  category?: T;
  author?: T;
  tags?: T;
  relatedPosts?: T;
  availableLocales?: T;
  featured?: T;
  publishedAt?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonicalOverride?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  icon?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        serviceHero?: T | ServiceHeroBlockSelect<T>;
        hiringModels?: T | HiringModelsBlockSelect<T>;
        logoCloud?: T | LogoCloudBlockSelect<T>;
        industries?: T | IndustriesBlockSelect<T>;
        talentShowcase?: T | TalentShowcaseBlockSelect<T>;
        cardGrid?: T | CardGridBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        process?: T | ProcessBlockSelect<T>;
        testimonials?: T | TestimonialsBlockSelect<T>;
        faq?: T | FaqBlockSelect<T>;
        postsTeaser?: T | PostsTeaserBlockSelect<T>;
        techStack?: T | TechStackBlockSelect<T>;
        cta?: T | CtaBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        contact?: T | ContactBlockSelect<T>;
        booking?: T | BookingBlockSelect<T>;
        sharedSection?: T | SharedSectionBlockSelect<T>;
      };
  parent?: T;
  relatedServices?: T;
  order?: T;
  menuRoles?:
    | T
    | {
        label?: T;
        id?: T;
      };
  availableLocales?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonicalOverride?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs_select".
 */
export interface JobsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  description?: T;
  requirements?: T;
  benefits?: T;
  department?: T;
  location?: T;
  workModel?: T;
  employmentType?: T;
  countryCode?: T;
  city?: T;
  validThrough?: T;
  availableLocales?: T;
  roleStatus?: T;
  publishedAt?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonicalOverride?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  decorative?: T;
  caption?: T;
  credit?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        content?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applicant-files_select".
 */
export interface ApplicantFilesSelect<T extends boolean = true> {
  originalName?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-applications_select".
 */
export interface JobApplicationsSelect<T extends boolean = true> {
  fullName?: T;
  email?: T;
  phone?: T;
  linkedin?: T;
  job?: T;
  cv?: T;
  coverNote?: T;
  status?: T;
  dedupeKey?: T;
  locale?: T;
  sourcePath?: T;
  utmSource?: T;
  utmMedium?: T;
  utmCampaign?: T;
  referrer?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  fullName?: T;
  email?: T;
  phone?: T;
  company?: T;
  subject?: T;
  message?: T;
  status?: T;
  locale?: T;
  sourcePath?: T;
  utmSource?: T;
  utmMedium?: T;
  utmCampaign?: T;
  referrer?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  items?:
    | {
        link?: {
          type?: ('internal' | 'route' | 'external') | null;
          /**
           * Visible link text. A link with no label is not rendered.
           */
          label?: string | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null)
            | ({
                relationTo: 'services';
                value: number | Service;
              } | null)
            | ({
                relationTo: 'jobs';
                value: number | Job;
              } | null);
          route?:
            ('/' | '/blog' | '/services' | '/careers' | '/contact' | '/meeting' | '/about' | '/meet-fika-ai') | null;
          url?: string | null;
          newTab?: boolean | null;
          /**
           * Optional. Sent as the GA4 event name when clicked (22.5).
           */
          analyticsId?: string | null;
        };
        children?:
          | {
              link?: {
                type?: ('internal' | 'route' | 'external') | null;
                /**
                 * Visible link text. A link with no label is not rendered.
                 */
                label?: string | null;
                reference?:
                  | ({
                      relationTo: 'pages';
                      value: number | Page;
                    } | null)
                  | ({
                      relationTo: 'posts';
                      value: number | Post;
                    } | null)
                  | ({
                      relationTo: 'services';
                      value: number | Service;
                    } | null)
                  | ({
                      relationTo: 'jobs';
                      value: number | Job;
                    } | null);
                route?:
                  | ('/' | '/blog' | '/services' | '/careers' | '/contact' | '/meeting' | '/about' | '/meet-fika-ai')
                  | null;
                url?: string | null;
                newTab?: boolean | null;
                /**
                 * Optional. Sent as the GA4 event name when clicked (22.5).
                 */
                analyticsId?: string | null;
              };
              description?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  ctas?:
    | {
        variant?: ('primary' | 'secondary' | 'ghost') | null;
        link?: {
          type?: ('internal' | 'route' | 'external') | null;
          /**
           * Visible link text. A link with no label is not rendered.
           */
          label?: string | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null)
            | ({
                relationTo: 'services';
                value: number | Service;
              } | null)
            | ({
                relationTo: 'jobs';
                value: number | Job;
              } | null);
          route?:
            ('/' | '/blog' | '/services' | '/careers' | '/contact' | '/meeting' | '/about' | '/meet-fika-ai') | null;
          url?: string | null;
          newTab?: boolean | null;
          /**
           * Optional. Sent as the GA4 event name when clicked (22.5).
           */
          analyticsId?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  announcement?: {
    enabled?: boolean | null;
    text?: string | null;
    link?: {
      type?: ('internal' | 'route' | 'external') | null;
      /**
       * Visible link text. A link with no label is not rendered.
       */
      label?: string | null;
      reference?:
        | ({
            relationTo: 'pages';
            value: number | Page;
          } | null)
        | ({
            relationTo: 'posts';
            value: number | Post;
          } | null)
        | ({
            relationTo: 'services';
            value: number | Service;
          } | null)
        | ({
            relationTo: 'jobs';
            value: number | Job;
          } | null);
      route?: ('/' | '/blog' | '/services' | '/careers' | '/contact' | '/meeting' | '/about' | '/meet-fika-ai') | null;
      url?: string | null;
      newTab?: boolean | null;
      /**
       * Optional. Sent as the GA4 event name when clicked (22.5).
       */
      analyticsId?: string | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  tagline?: string | null;
  blurb?: string | null;
  columns?:
    | {
        title: string;
        links?:
          | {
              link?: {
                type?: ('internal' | 'route' | 'external') | null;
                /**
                 * Visible link text. A link with no label is not rendered.
                 */
                label?: string | null;
                reference?:
                  | ({
                      relationTo: 'pages';
                      value: number | Page;
                    } | null)
                  | ({
                      relationTo: 'posts';
                      value: number | Post;
                    } | null)
                  | ({
                      relationTo: 'services';
                      value: number | Service;
                    } | null)
                  | ({
                      relationTo: 'jobs';
                      value: number | Job;
                    } | null);
                route?:
                  | ('/' | '/blog' | '/services' | '/careers' | '/contact' | '/meeting' | '/about' | '/meet-fika-ai')
                  | null;
                url?: string | null;
                newTab?: boolean | null;
                /**
                 * Optional. Sent as the GA4 event name when clicked (22.5).
                 */
                analyticsId?: string | null;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  newsletter?: {
    enabled?: boolean | null;
    heading?: string | null;
    body?: string | null;
  };
  /**
   * Privacy, cookies, terms (1.10 / 21.7).
   */
  legalLinks?:
    | {
        link?: {
          type?: ('internal' | 'route' | 'external') | null;
          /**
           * Visible link text. A link with no label is not rendered.
           */
          label?: string | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null)
            | ({
                relationTo: 'services';
                value: number | Service;
              } | null)
            | ({
                relationTo: 'jobs';
                value: number | Job;
              } | null);
          route?:
            ('/' | '/blog' | '/services' | '/careers' | '/contact' | '/meeting' | '/about' | '/meet-fika-ai') | null;
          url?: string | null;
          newTab?: boolean | null;
          /**
           * Optional. Sent as the GA4 event name when clicked (22.5).
           */
          analyticsId?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  legalName?: string | null;
  tagline?: string | null;
  logoLight?: (number | null) | Media;
  logoDark?: (number | null) | Media;
  /**
   * 1200x630. Fallback for every page without its own social image (18.7).
   */
  defaultOgImage?: (number | null) | Media;
  /**
   * Emitted as Organization.sameAs for entity disambiguation (19.4).
   */
  socialProfiles?:
    | {
        platform: 'linkedin' | 'whatsapp' | 'x' | 'facebook' | 'instagram' | 'youtube' | 'github';
        url: string;
        id?: string | null;
      }[]
    | null;
  offices?:
    | {
        city: string;
        country: string;
        addressLine?: string | null;
        phone?: string | null;
        email?: string | null;
        countryCode?: string | null;
        mapUrl?: string | null;
        isHeadquarters?: boolean | null;
        id?: string | null;
      }[]
    | null;
  generalEmail?: string | null;
  /**
   * Where contact form messages are delivered (11.4).
   */
  notificationEmails?: string[] | null;
  /**
   * Where job applications are delivered (10.6).
   */
  careersEmails?: string[] | null;
  /**
   * Default 30-minute booking link (12.2).
   */
  calendlyUrl?: string | null;
  ga4MeasurementId?: string | null;
  gtmContainerId?: string | null;
  linkedinPartnerId?: string | null;
  /**
   * 21.8 — controls when analytics tags are allowed to load.
   */
  consentMode?: ('opt-in' | 'essential') | null;
  defaultTitleSuffix?: string | null;
  defaultDescription?: string | null;
  /**
   * Search/discovery bots are configured separately from AI training crawlers (19.8/19.9). Document the decision before launch.
   */
  crawlerPolicy?: {
    allowSearchEngines?: boolean | null;
    allowAiSearchBots?: boolean | null;
    allowAiTrainingBots?: boolean | null;
    publishLlmsTxt?: boolean | null;
  };
  /**
   * google-site-verification content value (18.14).
   */
  searchConsoleVerification?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  items?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              label?: T;
              reference?: T;
              route?: T;
              url?: T;
              newTab?: T;
              analyticsId?: T;
            };
        children?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    label?: T;
                    reference?: T;
                    route?: T;
                    url?: T;
                    newTab?: T;
                    analyticsId?: T;
                  };
              description?: T;
              id?: T;
            };
        id?: T;
      };
  ctas?:
    | T
    | {
        variant?: T;
        link?:
          | T
          | {
              type?: T;
              label?: T;
              reference?: T;
              route?: T;
              url?: T;
              newTab?: T;
              analyticsId?: T;
            };
        id?: T;
      };
  announcement?:
    | T
    | {
        enabled?: T;
        text?: T;
        link?:
          | T
          | {
              type?: T;
              label?: T;
              reference?: T;
              route?: T;
              url?: T;
              newTab?: T;
              analyticsId?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  tagline?: T;
  blurb?: T;
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    label?: T;
                    reference?: T;
                    route?: T;
                    url?: T;
                    newTab?: T;
                    analyticsId?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  newsletter?:
    | T
    | {
        enabled?: T;
        heading?: T;
        body?: T;
      };
  legalLinks?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              label?: T;
              reference?: T;
              route?: T;
              url?: T;
              newTab?: T;
              analyticsId?: T;
            };
        id?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  legalName?: T;
  tagline?: T;
  logoLight?: T;
  logoDark?: T;
  defaultOgImage?: T;
  socialProfiles?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  offices?:
    | T
    | {
        city?: T;
        country?: T;
        addressLine?: T;
        phone?: T;
        email?: T;
        countryCode?: T;
        mapUrl?: T;
        isHeadquarters?: T;
        id?: T;
      };
  generalEmail?: T;
  notificationEmails?: T;
  careersEmails?: T;
  calendlyUrl?: T;
  ga4MeasurementId?: T;
  gtmContainerId?: T;
  linkedinPartnerId?: T;
  consentMode?: T;
  defaultTitleSuffix?: T;
  defaultDescription?: T;
  crawlerPolicy?:
    | T
    | {
        allowSearchEngines?: T;
        allowAiSearchBots?: T;
        allowAiTrainingBots?: T;
        publishLlmsTxt?: T;
      };
  searchConsoleVerification?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}